platform: x64
image: Visual Studio 2017
environment:
  matrix:
    - ARCH: x86
    - ARCH: x86_64
cache:
  - '%LOCALAPPDATA%\dub -> dub.selections.json'
install:
  - ps: function extractCompiler
        {
          pushd c:\\;
          7z x ldc.7z > $null;
          popd;
        }
  - ps: $latest = (Invoke-WebRequest "https://ldc-developers.github.io/LATEST").toString().replace("`n","").replace("`r","")
  - ps: $url = "https://github.com/ldc-developers/ldc/releases/download/v$($latest)/ldc2-$($latest)-windows-multilib.7z";
  - ps: Invoke-WebRequest $url -OutFile "c:\ldc.7z"
  - ps: extractCompiler
  - ps: $env:PATH += ";C:\ldc2-$($latest)-windows-multilib\bin;"
build_script:
  - dub build --arch=%ARCH% --compiler=ldc2 --build=release
after_build:
  - if defined APPVEYOR_REPO_TAG_NAME (set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%)
  - if not defined APPVEYOR_REPO_TAG_NAME (set TAG_NAME=untagged)
  - 7z -mx=9 a dls-%TAG_NAME%.windows.%ARCH%.zip dls.exe LICENSE.txt
test_script:
  - dub test --arch=%ARCH% --compiler=ldc2
artifacts:
  - path: dls-*.zip
deploy:
  - provider: GitHub
    auth_token: $(GITHUB_API_KEY)
    artifact: /dls-.*\.zip/
    on:
      appveyor_repo_tag: true