language: d
d: dmd
os:
  - linux
  - osx
env:
  - ARCH=x86
  - ARCH=x86_64
addons:
  apt:
    packages:
      - gcc-multilib
      - libcurl4-openssl-dev
script:
  - dub test --arch=$ARCH --compiler=$DC
before_deploy:
  - dub build --build=release --arch=$ARCH --compiler=$DC
  - mv dls dls-$TRAVIS_TAG.$TRAVIS_OS_NAME.$ARCH.run
deploy:
  provider: releases
  api_key:
    secure: $SECURE_API_KEY
  file: dls-$TRAVIS_TAG.$TRAVIS_OS_NAME.$ARCH.run
  skip_cleanup: true
  on:
    repo: LaurentTreguier/dls
    tags: true
