language: d
d: dmd
os:
  - linux
  - osx
env:
  - ARCH=x86
  - ARCH=x86_64
addons:
  apt:
    packages:
      - gcc-multilib
before_script:
  - ln -s /usr/bin/ld.gold ~/ld
script:
  - export PATH="$HOME:$PATH"
  - dub test --arch=$ARCH --compiler=$DC
  - dub build --build=release --arch=$ARCH --compiler=$DC
before_deploy:
  - strip dls
  - zip dls-${TRAVIS_TAG:-untagged}.$TRAVIS_OS_NAME.$ARCH.zip dls
deploy:
  provider: releases
  api_key:
    secure: $SECURE_API_KEY
  file: dls-*.zip
  skip_cleanup: true
  on:
    repo: LaurentTreguier/dls
    tags: true
