language: d
d: dmd
os:
  - linux
  - osx
env:
  - ARCH=x86
  - ARCH=x86_64
addons:
  apt:
    packages:
      - gcc-multilib
script:
  - dub test --arch=$ARCH
before_deploy:
  - dub build --build=release --arch=$ARCH
  - mv dls dls-$TRAVIS_TAG.$TRAVIS_OS_NAME.$ARCH.run
deploy:
  provider: releases
  api_key:
    secure: $SECURE_API_KEY
  file: dls-$TRAVIS_TAG.$TRAVIS_OS_NAME.$ARCH.run
  on:
    repo: LaurentTreguier/dls
    tags: true
